# Generated by Django 5.0.6 on 2024-06-29 06:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseekerprofile',
            options={'verbose_name': 'job seeker profile', 'verbose_name_plural': 'job seeker profiles'},
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='password',
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='dob',
            field=models.DateField(verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='educational_info',
            field=models.TextField(blank=True, null=True, verbose_name='educational information'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(choices=[(1, 'Job Seeker'), (2, 'Employer')], default=1)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.customuser'),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='username')),
                ('logo', models.ImageField(upload_to='employer_logos/', verbose_name='logo')),
                ('website', models.URLField(verbose_name='website URL')),
                ('address', models.TextField(verbose_name='address')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='newapp.customuser')),
            ],
            options={
                'verbose_name': 'employer profile',
                'verbose_name_plural': 'employer profiles',
            },
        ),
    ]
