# Generated by Django 5.0.6 on 2024-07-01 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_verifieduser_job_jobapplication_employernotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempJobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='username')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='temp_profile_pictures/', verbose_name='profile picture')),
                ('educational_info', models.TextField(blank=True, null=True, verbose_name='educational information')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='selectedjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='selectedjob',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='address',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='employer_profile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='job_seeker',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='jobs',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='website',
        ),
        migrations.CreateModel(
            name='Notification1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='JobSeekerNotification',
        ),
        migrations.DeleteModel(
            name='SelectedJob',
        ),
    ]
