# Generated by Django 5.0.6 on 2024-07-03 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_employer_tempemployerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='name',
            new_name='company_name',
        ),
    ]
